name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.3.0

    - name: cuda-toolkit
      uses: Jimver/cuda-toolkit@v0.2.8 

    - name: build
      run:  whoami  |
            cmake -S . -B Gpufit-build/ -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
            
    - name: make
      run:  cmake --build Gpufit-build/ --target all

    - name: misc
      run:  ./Gpufit-build/Gpufit_Cpufit_Performance_Comparison
